# Estruturas de repetição com tabelas

Renato Naville Watananbe

## Preparação do ambiente

In [9]:
def increase_font(): # importante ao dar aula. aumenta o tamanho da fonte
  from IPython.display import Javascript
  display(Javascript('''
  for (rule of document.styleSheets[0].cssRules){
    if (rule.selectorText=='body') {
      rule.style.fontSize = '36px'
      break
    }
  }
  '''))
get_ipython().events.register('pre_run_cell', increase_font)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Varrendo um array do Numpy


Você pode usar um loop for (ou while) para ler valores individuais de arrays do Numpy. Lembre-se que o índice de um array do Numpy começa de 0. Então ao chamar `x[0]`, o programa vai acessar o primeiro valor de `x`.



In [20]:
import numpy as np


x = np.array([2, -0.9, 4.5, -3, 1, 8, 5])

for i in range(len(x)):
    print(f'i={i}, x[{i}]={x[i]}')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

i=0, x[0]=2.0
i=1, x[1]=-0.9
i=2, x[2]=4.5
i=3, x[3]=-3.0
i=4, x[4]=1.0
i=5, x[5]=8.0
i=6, x[6]=5.0


Por exemplo, se quisermos computar a classificação do IMC (ver [aula 4](https://nbviewer.jupyter.org/format/slides/github/rnwatanabe/BasesComputacionais2019/blob/master/aula4/EstruturasCondicionais.ipynb#/27)) para três pessoas, podemos gravar a massa e altura em arrays do Numpy e dentro de um for ler um valor por vez. Por exemplo, para $m_1 = 51$ kg e $h_1=1,51$ m, $m_2 = 78$ kg e $h_2=1,75$ m e $m_3 = 51$ kg e $h_3=1,51$ m , temos:

In [22]:
m = np.array([51, 78, 67])
h = np.array([1.51, 1.75, 1.94])

for i in range(len(m)):
    IMC= m[i]/h[i]**2
    if  IMC <= 17:
        print (f'O IMC para m = {m[i]} kg e h = {h[i]} m é {IMC:.2f} e é classificado como Muito abaixo do peso')
    if  IMC > 17 and IMC <= 18.5:
        print(f'O IMC para m = {m[i]} kg e h = {h[i]} m é {IMC:.2f} e  é classificado como Abaixo do peso')
    if  IMC > 18.5 and IMC <= 25:
        print(f'O IMC para m = {m[i]} kg e h = {h[i]} m é {IMC:.2f} e  é classificado como Peso Normal')
    if  IMC > 25 and IMC <= 30:
        print (f'O IMC para m = {m[i]} kg e h = {h[i]} m é {IMC:.2f} e  é classificado como Acima do Peso')
    if  IMC > 30 and IMC <= 35:
        print (f'O IMC para m = {m[i]} kg e h = {h[i]} m é {IMC:.2f} e  é classificado como Obesidade Grau I')
    if  IMC > 35 and IMC <= 40:
        print (f'O IMC para m = {m[i]} kg e h = {h[i]} m é {IMC:.2f} e  é classificado como Obesidade Grau II')
    if  IMC > 40:
        print (f'O IMC para m = {m[i]} kg e h = {h[i]} m é {IMC:.2f} e  é classificado como Obesidade Grau III')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

O IMC para m = 51 kg e h = 1.51 m é 22.37 e  é classificado como Peso Normal
O IMC para m = 78 kg e h = 1.75 m é 25.47 e  é classificado como Acima do Peso
O IMC para m = 67 kg e h = 1.94 m é 17.80 e  é classificado como Abaixo do peso


### Gravando valores em um array do Numpy



É possível alterar os valores de um array do Numpy elemento a elemento. Para fazer isso, basta atribuir o valor desejado `n` ao i-ésimo elemento do array:

`x[i] = n`

É claro que para fazer isso, é necessário que o array exista. Normalmente, se você planeja atribuir os valores de um array elemento a elemento, é criado um array em que todos os elementos são iguais a zero. Isso pode ser feito com a função `np.zeros(N)`, em que `N` define o tamanho do array.

No código abaixo é criado um array com 5 elementos e esses elementos são preenchidos um a um.

In [25]:
x = np.zeros(6)

x[0] = 11
x[1] = 13
x[2] = 15
x[3] = 17
x[4] = 19
x[5] = 21

x

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([11., 13., 15., 17., 19., 21.])

Podemos fazer essa atribuição dentro de um laço for.

In [26]:
x = np.zeros(6)

for i in range(len(x)):
  x[i] = 11 + 2*i
x

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([11., 13., 15., 17., 19., 21.])


**Loops com arrays do Numpy devem ser utilizados como último recurso. Na maioria das situações os comandos do Numpy são suficientes. Em geral é necessário usar um loop quando os elementos dos arrays dependem dos elementos anteriores.**

Por exemplo, o último laço poderia facilmente ser substituído por:

In [27]:
i = np.arange(0, 6)
x = 11+2*i
x

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([11, 13, 15, 17, 19, 21])



Porém, quando um elemento do array depende dos valores de elementos anteriores do array, não há alternativa a não ser usar um laço.


Por exemplo, podemos querer gravar os 30 primeiros elementos da série de Fibonacci em um array (um elemento da série de Fibonacci é a soma dos dois elementos anteriores da série, em que os dois primeiros elementos são iguais a 1):

In [23]:
fib = np.zeros(30, dtype=int)

fib[0] = 1
fib[1] = 1
for i in range(2, len(fib)):
    fib[i] = fib[i-1] + fib[i-2]

fib

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([     1,      1,      2,      3,      5,      8,     13,     21,
           34,     55,     89,    144,    233,    377,    610,    987,
         1597,   2584,   4181,   6765,  10946,  17711,  28657,  46368,
        75025, 121393, 196418, 317811, 514229, 832040])

Repare que antes de começar a gravar os valores no array fib, é necessário criá-lo. Isso é feito com o comando 'np.zeros(N)', em que N é o número de elementos que o array tem. Além disso, os dois primeiros elementos da série de Fibonacci devem ter os seus valores designados antes de começar o loop for, já que eles não seguem a regra de serem uma soma dos dois elementos anteriores.

### Lendo e gravando valores em um DataFrame do Pandas



In [13]:
import pandas as pd


compras = pd.read_csv('https://raw.githubusercontent.com/BMClab/BasesComputacionais/master/dados/compras.csv')
compras


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Produto Fabricante  Qtd Medida  Preço Supermercado        Data
0     Suco   ValeSuco    1      l   3.00     Arpoador  12/05/2011
1     Suco      Flash    1      l   4.50     Arpoador  18/05/2011
2   Tomate         -     1     kg   3.50        Noite  14/05/2011
3    Arroz   Tio José    4     kg   8.64        Noite  14/05/2011
4    Arroz  Sem Broto    5     kg   9.99     Arpoador  10/06/2011
5    Arroz      Da TV    1     kg   1.99        Noite  14/06/2011
6   Feijão  Sem Broto    1     kg   4.00     Arpoador  12/05/2011
7   Tomate         -     1     kg   2.99        Noite  16/05/2011
8      Ovo   A Granja   12      u   3.19     Arpoador  12/06/2011
9      Ovo    Caseiro    6      u   1.45        Noite  14/05/2011
10    Suco      Flash    1      l   3.99        Noite  21/07/2011

Existem diversas maneiras para ler o valor de uma posição específica de um DataFrame.

Uma delas é acrescentando o comando '.values' após o nome do campo do DataFrame e, entre colchetes, colocar o índice do item desejado.

In [14]:
compras['Produto'].values[3]

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

'Arroz'

Uma outra maneira é com a função `.at[*linha*, *coluna*]` acrescentado após o nome do DataFrame.

In [15]:
compras.at[3, 'Produto']

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

'Arroz'

Por exemplo, podemos usar um laço for para designar valores a um novo DataFrame.

Primeiro é necessário criar um DataFrame sem valores. É necessário determinar quais serão as colunas e quais serão as linhas.

In [16]:
meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
         'Julho', 'Agosto', 'Setembro','Outubro', 'Novembro', 'Dezembro']

colunas = ['Mês', 'Quantidade']
quantidade = pd.DataFrame(0, index=np.arange(0, 12, 1), columns=colunas)
quantidade['Mês'] = meses
quantidade

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Mês  Quantidade
0     Janeiro           0
1   Fevereiro           0
2       Março           0
3       Abril           0
4        Maio           0
5       Junho           0
6       Julho           0
7      Agosto           0
8    Setembro           0
9     Outubro           0
10   Novembro           0
11   Dezembro           0

Agora, pode-se usar um laço for para ler o DataFrame 'compras' e gravar no Dataframe 'quantidade' a quantidade de produtos em cada mês.

In [17]:
compras['Data'] = pd.to_datetime(compras['Data'], format='%d/%m/%Y')

for i in range(len(compras)):
    quantidade.at[compras.at[i, 'Data'].month - 1, 'Quantidade'
                  ] = (quantidade.at[compras.loc[i, 'Data'].month - 1, 'Quantidade']
                       + compras.at[i, 'Qtd'])

quantidade

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Mês  Quantidade
0     Janeiro           0
1   Fevereiro           0
2       Março           0
3       Abril           0
4        Maio          15
5       Junho          18
6       Julho           1
7      Agosto           0
8    Setembro           0
9     Outubro           0
10   Novembro           0
11   Dezembro           0

### Exercícios

- Escrever um notebook do Colab para fazer o que pedido a seguir.





**1)**  Três séries, $v, y$ e $t$ seguem as seguintes regras:
        
$$v[i] = v[i-1] + 0,01.(-9,81)$$
$$y[i] = y[i-1] + 0,01v[i-1]$$
$$t[i] = t[i-1] + 0,01$$
        
Começando com v[0] = 10 m/s, y[0] = 0 m e t[0] = 0 s, calcule os 250 primeiros valores das três séries.

Faça os gráficos com os valores encontrados de $y$ em função de $t$ e dos valores encontrados de $v$ em função de $t$.

Observação: o cálculo destas três séries é uma simulação computacional para calcular a posição e velocidade de uma partícula lançada na vertical com velocidade inicial de 10 m/s. O método utilizado para realizar esta simulação é conhecido como método de Euler. Como uma série depende da outra, os cálculo das três séries devem ser feitos dentro do mesmo laço.


**2)** Calcular a aproximação de uma onda quadrada seguindo a seguinte expressão (a expressão abaixo é calculada utilizando uma teoria matemática conhecida como série de Fourier):

$$x(t)  \approx \frac{4}{\pi}\displaystyle \sum_{i = 1}^N \frac{\mathrm{sen}\left[(2i - 1)t\right]}{2i - 1}$$

Faça a aproximação para $0 \leqslant t \leqslant 10$ (utilize um número suficiente de pontos no array $t$ para poder observar o gráfico de $x(t)$, algo em torno de 100000 pontos).

Faça a aproximação para a) N = 10, b) N = 100, c) N = 1000 e d) N = 10000. Coloque todas as aproximações em um único gráfico, com a aproximação de $x(t)$ em função de $t$.

Dica: se você estiver com dificuldade, faça primeiro o gráfico considerando i = 1, sem nenhuma somatória (N = 1). Depois disso, coloque o código que você tiver escrito dentro de um for ou while para variar o valor de i e fazer a somatória.



### Referências

- Chalco, JM, *Slides de Bases Computacionais da Ciência*, (2014)
- Leite, S, *Slides de Bases Computacionais da Ciência*, (2018)
- [Marietto, MGB et al.; **Bases computacionais da Ciência** (2013)](http://prograd.ufabc.edu.br/images/pdf/bases_computacionais_livro.pdf).
- [Ipeadata](http://www.ipeadata.gov.br)